import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillGithub, AiFillLinkedin, AiFillFacebook, AiFillInstagram} from "react-icons/ai";
import Image from 'next/image';
import deved from "/Users/shahmeerqureshi98/react-portfolio/public/software-developer-copy.png";

export default function Home() {
  return (
    <><div>
      <Head>
        <title>Shahmeer Qureshi Portfolio</title>
        <meta name="description" content="Generated by creating" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    
    <main className=" bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons font-bold text-black">Shahmeer&apos;s Portfolio</h1>
            <ul className="flex items-center">
              <li className="text-black">
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li className="text-black">
                <a className="bg-gradient-to-r from-emerald-500 to-green-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-green-600 font-bold'>Shahmeer Qureshi</h2>
            <h3 className='text-black font-semibold text-2xl py-10'>Software Engineer Graduate</h3>
            <p className='text-md py-5 leading-8 text-left text-gray-800'>
              Welcome to my personal portfolio! My name is Shahmeer Qureshi and I am a recent Computer Engineer graduate from 
              Toronto Metropolitan University. On April 2023, I successfully completed my education and received my degree.
              As a passionate and dedicated individual, I am eager to embark on my professional journey in the software engineering 
              field and make a significant impact. Proficient in languages such as Python/Flask, Java, and JavaScript (Node, React), 
              along with experience in HTML, CSS, C/C++, SQL/SQLite, Git, VHDL, MATLAB, and JavaFX/Scene Builder, I am 
              well-equipped to handle diverse software engineering tasks. With a team-oriented mindset and a proven ability to 
              work effectively within groups, I thrive in collaborative environments and actively contribute to the achievement 
              of shared goals. My academic journey has equipped me with valuable problem-solving skills, critical thinking abilities, 
              and a keen eye for detail. I am eager to apply my theoretical knowledge and collaborate with industry professionals 
              to create innovative and efficient solutions. This portfolio showcases my projects, skills, and experiences, 
              demonstrating my ability to deliver high-quality code and contribute effectively to any development team. 
              Proactive, adaptable, and eager to gain practical experience,  I am excited to kick-start my career on a 
              high note and make a lasting impression on potential employers. Thank you for visiting my portfolio, 
              and I look forward to the opportunity to connect and discuss how I can bring value to your organization.
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillInstagram />
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-emerald-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src="/software-developer-copy.png" alt="Software Developer" fill style/>
          </div>

        </section>
        
    <section>
      <div>
        <h3 className='text-black font-bold text-3xl text-center pt-16 pb-8'>My Projects</h3>
        <p className='text-black leading-5 p-5'>
        <p class='font-bold text-md '>Capstone Project: AI-based Job Recommender System</p>
        <p class='font-semibold text-md py-3'>Toronto Metropolitan University | Sept 2022 - Apr 2023</p>
        <ul className='p-5'> • Led a team of four engineers to conceptualize, design and develop a cutting- edge job recommender system with a custom web scraper and resume parser for job recommendations </ul>
        <ul className='p-5'> • Designed and executed the frontend interface utilizing Tailwind CSS, HTML and JavaScript to ensure a modern and user-friendly experience </ul>
        <ul className='p-5'> • Engineered a robust and scalable backend using Python, Flask and SQLite, managing complex data models and business logic </ul>
        <ul className='p-5'> • Machine learning algorithms were constructed to analyze job seeker data and recommend relevant job postings </ul> </p>

        <p className='text-black leading-5 p-5'>
        <p class='font-bold text-md '>Java Snake Game</p>
        <p class='font-semibold text-md py-3'>Personal Project | Feb 2023 - Mar 2023</p>
        <ul className='p-5'> • Developed a classic Snake game using Java&apos;s Swing library and applying Object- Oriented Programming principles to create a modular and maintainable codebase </ul>
        <ul className='p-5'> • Implemented interactive gameplay with user-controlled snake movement, apple collection for scoring, and dynamic snake growth </ul>
        <ul className='p-5'> • Ensured bug-free functionality through comprehensive testing and incorporated features like collision detection and game-ending conditions </ul></p>

        <p className='text-black leading-5 p-5'>
        <p class='font-bold text-md '>JavaFX GUI Bookstore Application</p>
        <p class='font-semibold text-md py-3'>Toronto Metropolitan University | Mar 2021 - Apr 2021</p>
        <ul className='p-5'> • Applied Object-Oriented concepts and utilized JavaFX for user-friendly book purchasing with points system </ul>
        <ul className='p-5'> • Implemented customer and book classes for seamless functionality </ul>
        <ul className='p-5'> • Created owner login to manage customer accounts, view earned points, and administer customer and book information </ul>
        <ul className='p-5'> • Enabled customer login to select books, earn points per purchase, and redeem points for additional books </ul></p>

        <p className='text-black leading-5 p-5'>
        <p class='font-bold text-md '>Arithmetic and Logic Unit (ALU): Design & Implementation</p>
        <p class='font-semibold text-md py-3'>Toronto Metropolitan University | Jun 2020 – Aug 2020</p>
        <ul className='p-5'> • Implemented Arithmetic Logic Unit (ALU) using VHDL coding, consisting of components such as Latch, Finite State Machine (FSM), and 4:16 Decoder </ul>
        <ul className='p-5'> • Created truth tables and simulated waveforms for each component to validate functionality </ul>
        <ul className='p-5'> • Modified ALU to perform a variety of operations </ul></p>


      </div>
    </section>

    </main>
      </>
  )
}
